apiVersion: v1
kind: Pod
metadata:
  name: abctechnologiesapp
  labels:
    app: abctechnologiesapp
spec:
  containers:
  - name: abctechnologiesapp
    image: ucfrance/abctechnologies

    ports:
    - containerPort: 8080
