apiVersion: apps/v1
kind: Deployment
metadata:
  name: abctechnologiesappdeployment
spec:
  selector:
    matchLabels:
      app: abctechnologiesapp
  replicas: 2
  template:
    metadata:
      name: abctechnologiesapppod
      labels:
        app: abctechnologiesapp
    spec:
      containers:
      - name: abctechnologiescontainer
        image: ucfrance/abctechnologies
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m" 
        ports:
        - containerPort: 8080
      
---
apiVersion: v1
kind: Service
metadata:
  name: abctechnologiesapp
spec:
  selector:
    app: abctechnologiesapp
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
