apiVersion: apps/v1
kind: Deployment
metadata:
  name: abctechnologiesapp
  labels:
    app: abctechnologiesapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: abctechnologiesapp
    spec:
      containers:
      - name: abctechnologiesapp
        image: ucfrance/abctechnologies
        ports:
        - containerPort: 8080
  selector:
    matchLabels:
      app: abctechnologiesapp
      
---
apiVersion: v1
kind: Service
metadata:
  name: abctechnologiesapp
spec:
  selector:
    app: abctechnologiesapp
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
